import loadBlogsData from "@/utils/loadBlogsData";
import Link from "next/link";
import React from "react";

export const metadata = {
  title: "Blogs | Bike Innovate - Next.js",
  description: "Generated by create next app",
};

// const blogs = [
//   {
//     id: 1,
//     year: 2018,
//     title: "Blog-Title : 01",
//   },
//   {
//     id: 2,
//     year: 2019,
//     title: "Blog-Title : 02",
//   },
//   {
//     id: 3,
//     year: 2020,
//     title: "Blog-Title : 03",
//   },
//   {
//     id: 4,
//     year: 2021,
//     title: "Blog-Title : 04",
//   },
// ];

const BlogsPage = async () => {

  const blogs = await loadBlogsData();

  return (
    <div className="container mx-auto">
      <h2 className="text-center text-4xl my-8 font-semibold">Welcome to Blog{"'"}s Page</h2>

      <div className="grid grid-cols-3 gap-4">{blogs.map(({ id, body, title }) => (
        <div key={id} className="border border-blue-500 p-6 my-2 shadow-xl rounded-lg">
          <h2 className="text-2xl">{id}. {title}</h2>
          <p>{body}</p>
          <Link
              href={`/blogs/${id}`}
            // href={{
            //   pathname: `/blogs/${title}/${id}`,
            //   query: {
            //     title: title,
            //   },
            // }}
            className="inline-block mt-5"
          >
            <button className="btn btn-primary btn-sm mt-2 text-xl text-white relative bottom-2">Read Blog</button>
          </Link>
        </div>
      ))}</div>
    </div>
  );
};

export default BlogsPage;
