import React from 'react';

export const metadata = {
    title: "About | Bike Innovate - Next.js",
    description: "Generated by create next app",
  };

const AboutPage = () => {
    return (
        <div>
            <h1>About Page</h1>
        </div>
    );
};

export default AboutPage;