import React from 'react';


export const metadata = {
    title: "Dashboard | Bike Innovate - Next.js",
    description: "Generated by create next app",
  };

const DashboardPage = () => {
    return (
        <div>
            <h2>Welcome to Dashboard</h2>
        </div>
    );
};

export default DashboardPage;