import Image from 'next/image';
import React from 'react';
import bike from '@/assets/about-b.jpg';

export const metadata = {
    title: "Dashboard | Bike Innovate - Next.js",
    description: "Generated by create next app",
  };

const DashboardPage = () => {
    return (
        <div className='text-center text-4xl font-semibold container'>
            <h2 className='mt-6 mb-12'>Welcome to Dashboard</h2>
            <Image src={bike} alt=""></Image>
        </div>
    );
};

export default DashboardPage;